### ISSUE TITLE
Need to update Initial data import to match new models

### ISSUE THREAD

**Issue by OWLsync** [OWLsync/OWLsync#3]
error when running:

One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'Mapper|User|user'. Original exception was: When initializing mapper Mapper|User|user, expression 'Post' failed to locate a name ("name 'Post' is not defined"). If this is a class name, consider adding this relationship() to the class after both dependent classes have been defined.

**Comment by verpeteren** [comment]
see https://github.com/OWLsync/OWLsync/tree/20180116
